spring.application.name=notaventa
#Configuramos que abse de datos usaremos
spring.jpa.database=POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost/notaventa
spring.datasource.username=angelo
spring.datasource.password=viernes07/2003
spring.jpa.show-sql=true

